Question: From the given data, make predictions on why this restaurant is losing money

1. Looking over the information listed, I can already find some discrepancies in the data.
    a. The database is messy, and encoded. It will be tricky to access all information, the database will need to be updated, and personalized later.
    b. There's a lot of low cost items on the menu which should be leading to higher profits
2. First, I will convert the database into a database editor to continue, I chose “DB Browser for SQLite” 
3. Second I will use a join query to calculate three things
    a. The total cost to make the recipe
    b. The gross profit of the menu item
    c. The profit margin for each dish (based on ingredients excluding labor)
This will be the query I use: [`01_profit_margin_analysis.sql`](sql/01_profit_margin_analysis.sql)   
I can see that the Salad and pizza menu items are outliers, losing more money than other menu items. Though it isn't necessarily bad, as long as those items sell a lot. Lets check
I’ll use this query to check total amounts of each item sold (I also included the average price per order but later saw the information was of no value):
I can see once again Salad is an outlier. It is one of the lowest selling items on the menu. I can also see Pizza is the best seller, meaning this is not the root cause for the loss of money.
I can see salad is an outlier, but why. I will use a union query to see what ingredients cost most: 
I can see now Parmesan is the highest cost ingredient by sixty-five cents. Due to the salad being one of the lowest ordered items, and the high cost of the parmesan i believe this menu item is the cause for the loss of money
Recommendations: 
Regardless, start marketing the salad. Put up larger menu displays and posters to draw attention to the low sold menu/high cost menu item
Either, reduce amount of parmesan per salad by 1 oz, saving 62 cents per order
Or, look into changing the vinaigrette for a new parmesan dressing. Getting rid of the need for parmesan on the salad entirely. Depending on the new cost of the new dressing, this would save around one dollar per salad. And can be labeled as a new menu item for an event.
Doing these steps could save 100-200$ per week. This is good but perhaps theres more im missing
I’m going to go back to my original thought, the low cost menu items should be generating plenty of profit. I will use a join query to do many things here
List the menu item, menu cost, cost to make and gross profit
Count total quantity sold
Finally calculate its total profit contribution to search for discrepancies 
Here is the query: 
I can see from the chart theres a discrepancy from the low profit items. The low profit items are generating low total profit. 
The mains are selling extremely well, the sides and desserts are shaky
Ice cream, fries and salad are losing the most
Ice cream has a high cost and low total quantity sold
Fries have a high quantity sold but low gross per item
Salad has already been touched on
I’ll do one last SQL query to finalize and confirm my thoughts.
It will calculate the combined profit and total orders of the top 4 sellers and bottom 4 sellers
Averages the price per order
This will show me exactly the reason for the loss of income
Here is the query:
I can see theres no problem with the amount of orders, just the amount of profit generated by each item 
 Upping the prices or removing the items would be my first recommendation, but these are common items where both would be difficult to do without receiving backlash
My second thought is to introduce a discounted bundling system where customers can order more food at a slightly discounted price. 
Burger and fries
Pasta and salad
Pizza and icecream 
The discounted bundling system seems like a valid option. It is vague though so let me narrow it down. Either a full discount for both items, or simply just a discount on the side/dessert. 
I’ll use 2 separate quieres to figure this out. This will be the 10% off both items
	This query will be for 20% off the side/dessert item:
	I can see that rolling out the combo bundles with a 20% discount on the side/dessert item will increase profit and sales for low sales items such as fries and ice cream. 
Final thoughts
As a short win, change the salad recipe to include less parmesan. Perhaps adding more lower cost ingredients such as tomatoes or olives as a substitute
Long term, rework the menu to include combo bundles. These bundles should include a high sold/high profit item, with a lesser sold/less profit margin item. And placing a 20% discount on the cheaper item will lead to more item sales and higher profits overall without changing the menu or switching around any labor.
